spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5555/crypto_currency_db}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    show-sql: true
liquibase:
  scan:
    packages: com.miachyn.watcherservice
client:
  url: https://api.coinlore.net/api/ticker/
schedule:
  work: 3600000
